export const GET_BREEDS_REQUEST = 'GET_BREEDS_REQUEST';
export const GET_BREEDS_SUCCESS = 'GET_BREEDS_SUCCESS';
export const GET_BREEDS_ERROR = 'GET_BREEDS_ERROR';

export const GET_DOG_IMAGE_REQUEST = 'GET_DOG_IMAGE_REQUEST';
export const GET_DOG_IMAGE_SUCCESS = 'GET_DOG_IMAGE_SUCCESS';
export const GET_DOG_IMAGE_ERROR = 'GET_DOG_IMAGE_ERROR';
